/** Named Bangladesh Railway intercity services. Each runs in both directions. */
export interface TrainServiceSeed {
	id: string;
	name: string;
	/** Down and up train numbers, as printed on the timetable. */
	numbers: [string, string];
	origin: string;
	destination: string;
	layoutId: string;
	/** Local departure times (HH:MM) from origin, then from destination. */
	departTimes: string[];
	returnTimes: string[];
	/** Weekday the service rests, 0 = Sunday. Omitted means it runs daily. */
	offDay?: number;
	rating: number;
	ratingCount: number;
	fareIndex: number;
}

export const BD_TRAIN_SERVICES: TrainServiceSeed[] = [
	{
		id: 'subarna-express',
		name: 'Subarna Express',
		numbers: ['701', '702'],
		origin: 'dhaka',
		destination: 'chattogram',
		layoutId: 'train-intercity',
		departTimes: ['07:00'],
		returnTimes: ['15:00'],
		offDay: 1,
		rating: 43,
		ratingCount: 12400,
		fareIndex: 1.05
	},
	{
		id: 'sonar-bangla',
		name: 'Sonar Bangla Express',
		numbers: ['787', '788'],
		origin: 'dhaka',
		destination: 'chattogram',
		layoutId: 'train-intercity',
		departTimes: ['17:00'],
		returnTimes: ['07:00'],
		offDay: 2,
		rating: 45,
		ratingCount: 15230,
		fareIndex: 1.15
	},
	{
		id: 'mahanagar-provati',
		name: 'Mahanagar Provati',
		numbers: ['703', '704'],
		origin: 'dhaka',
		destination: 'chattogram',
		layoutId: 'train-intercity',
		departTimes: ['07:45'],
		returnTimes: ['19:20'],
		rating: 40,
		ratingCount: 9870,
		fareIndex: 0.95
	},
	{
		id: 'turna-nishitha',
		name: 'Turna Nishitha',
		numbers: ['741', '742'],
		origin: 'dhaka',
		destination: 'chattogram',
		layoutId: 'train-night',
		departTimes: ['23:30'],
		returnTimes: ['23:00'],
		rating: 42,
		ratingCount: 11060,
		fareIndex: 1.1
	},
	{
		id: 'chattala-express',
		name: 'Chattala Express',
		numbers: ['801', '802'],
		origin: 'dhaka',
		destination: 'chattogram',
		layoutId: 'train-intercity',
		departTimes: ['13:00'],
		returnTimes: ['08:30'],
		offDay: 2,
		rating: 38,
		ratingCount: 6420,
		fareIndex: 0.9
	},

	{
		id: 'parabat-express',
		name: 'Parabat Express',
		numbers: ['709', '710'],
		origin: 'dhaka',
		destination: 'sylhet',
		layoutId: 'train-intercity',
		departTimes: ['06:20'],
		returnTimes: ['15:45'],
		offDay: 2,
		rating: 43,
		ratingCount: 8940,
		fareIndex: 1.05
	},
	{
		id: 'jayantika-express',
		name: 'Jayantika Express',
		numbers: ['717', '718'],
		origin: 'dhaka',
		destination: 'sylhet',
		layoutId: 'train-intercity',
		departTimes: ['11:15'],
		returnTimes: ['11:45'],
		offDay: 4,
		rating: 39,
		ratingCount: 5610,
		fareIndex: 0.95
	},
	{
		id: 'upaban-express',
		name: 'Upaban Express',
		numbers: ['739', '740'],
		origin: 'dhaka',
		destination: 'sylhet',
		layoutId: 'train-night',
		departTimes: ['20:30'],
		returnTimes: ['23:30'],
		rating: 42,
		ratingCount: 7830,
		fareIndex: 1.1
	},
	{
		id: 'kalni-express',
		name: 'Kalni Express',
		numbers: ['773', '774'],
		origin: 'dhaka',
		destination: 'sylhet',
		layoutId: 'train-intercity',
		departTimes: ['14:50'],
		returnTimes: ['06:15'],
		offDay: 3,
		rating: 41,
		ratingCount: 6180,
		fareIndex: 1.0
	},

	{
		id: 'banalata-express',
		name: 'Banalata Express',
		numbers: ['791', '792'],
		origin: 'dhaka',
		destination: 'rajshahi',
		layoutId: 'train-intercity',
		departTimes: ['13:30'],
		returnTimes: ['07:00'],
		offDay: 5,
		rating: 46,
		ratingCount: 10240,
		fareIndex: 1.2
	},
	{
		id: 'silk-city-express',
		name: 'Silk City Express',
		numbers: ['753', '754'],
		origin: 'dhaka',
		destination: 'rajshahi',
		layoutId: 'train-intercity',
		departTimes: ['14:45'],
		returnTimes: ['07:40'],
		offDay: 0,
		rating: 42,
		ratingCount: 8120,
		fareIndex: 1.05
	},
	{
		id: 'padma-express',
		name: 'Padma Express',
		numbers: ['759', '760'],
		origin: 'dhaka',
		destination: 'rajshahi',
		layoutId: 'train-night',
		departTimes: ['22:45'],
		returnTimes: ['16:00'],
		offDay: 2,
		rating: 41,
		ratingCount: 7460,
		fareIndex: 1.05
	},
	{
		id: 'dhumketu-express',
		name: 'Dhumketu Express',
		numbers: ['769', '770'],
		origin: 'dhaka',
		destination: 'rajshahi',
		layoutId: 'train-intercity',
		departTimes: ['06:00'],
		returnTimes: ['23:20'],
		offDay: 4,
		rating: 40,
		ratingCount: 6540,
		fareIndex: 1.0
	},

	{
		id: 'sundarban-express',
		name: 'Sundarban Express',
		numbers: ['725', '726'],
		origin: 'dhaka',
		destination: 'khulna',
		layoutId: 'train-intercity',
		departTimes: ['08:15'],
		returnTimes: ['21:45'],
		offDay: 3,
		rating: 43,
		ratingCount: 9310,
		fareIndex: 1.1
	},
	{
		id: 'chitra-express',
		name: 'Chitra Express',
		numbers: ['763', '764'],
		origin: 'dhaka',
		destination: 'khulna',
		layoutId: 'train-night',
		departTimes: ['19:00'],
		returnTimes: ['09:00'],
		offDay: 1,
		rating: 41,
		ratingCount: 7120,
		fareIndex: 1.05
	},
	{
		id: 'jahanabad-express',
		name: 'Jahanabad Express',
		numbers: ['777', '778'],
		origin: 'dhaka',
		destination: 'khulna',
		layoutId: 'train-intercity',
		departTimes: ['16:20'],
		returnTimes: ['06:00'],
		rating: 40,
		ratingCount: 4210,
		fareIndex: 1.0
	},

	{
		id: 'rangpur-express',
		name: 'Rangpur Express',
		numbers: ['771', '772'],
		origin: 'dhaka',
		destination: 'rangpur',
		layoutId: 'train-night',
		departTimes: ['21:10'],
		returnTimes: ['08:10'],
		offDay: 0,
		rating: 42,
		ratingCount: 8640,
		fareIndex: 1.15
	},
	{
		id: 'kurigram-express',
		name: 'Kurigram Express',
		numbers: ['797', '798'],
		origin: 'dhaka',
		destination: 'kurigram',
		layoutId: 'train-night',
		departTimes: ['20:45'],
		returnTimes: ['07:20'],
		offDay: 3,
		rating: 40,
		ratingCount: 3980,
		fareIndex: 1.1
	},
	{
		id: 'ekota-express',
		name: 'Ekota Express',
		numbers: ['705', '706'],
		origin: 'dhaka',
		destination: 'dinajpur',
		layoutId: 'train-intercity',
		departTimes: ['10:10'],
		returnTimes: ['21:20'],
		rating: 39,
		ratingCount: 6270,
		fareIndex: 1.05
	},
	{
		id: 'drutojan-express',
		name: 'Drutojan Express',
		numbers: ['757', '758'],
		origin: 'dhaka',
		destination: 'dinajpur',
		layoutId: 'train-night',
		departTimes: ['20:00'],
		returnTimes: ['08:10'],
		rating: 40,
		ratingCount: 5840,
		fareIndex: 1.05
	},
	{
		id: 'panchagarh-express',
		name: 'Panchagarh Express',
		numbers: ['793', '794'],
		origin: 'dhaka',
		destination: 'panchagarh',
		layoutId: 'train-night',
		departTimes: ['22:45'],
		returnTimes: ['12:00'],
		rating: 43,
		ratingCount: 5120,
		fareIndex: 1.2
	},

	{
		id: 'tista-express',
		name: 'Tista Express',
		numbers: ['707', '708'],
		origin: 'dhaka',
		destination: 'jamalpur',
		layoutId: 'train-intercity',
		departTimes: ['07:30'],
		returnTimes: ['14:30'],
		offDay: 1,
		rating: 38,
		ratingCount: 4610,
		fareIndex: 0.9
	},
	{
		id: 'brahmaputra-express',
		name: 'Brahmaputra Express',
		numbers: ['743', '744'],
		origin: 'dhaka',
		destination: 'mymensingh',
		layoutId: 'train-intercity',
		departTimes: ['18:15'],
		returnTimes: ['06:30'],
		rating: 39,
		ratingCount: 5340,
		fareIndex: 0.92
	},
	{
		id: 'agnibina-express',
		name: 'Agnibina Express',
		numbers: ['735', '736'],
		origin: 'dhaka',
		destination: 'jamalpur',
		layoutId: 'train-intercity',
		departTimes: ['09:45'],
		returnTimes: ['17:00'],
		rating: 37,
		ratingCount: 3720,
		fareIndex: 0.88
	},
	{
		id: 'egarosindhur',
		name: 'Egarosindhur Provati',
		numbers: ['737', '738'],
		origin: 'dhaka',
		destination: 'kishoreganj',
		layoutId: 'train-intercity',
		departTimes: ['07:15', '18:40'],
		returnTimes: ['12:30', '06:20'],
		offDay: 3,
		rating: 38,
		ratingCount: 4180,
		fareIndex: 0.85
	},

	{
		id: 'coxs-bazar-express',
		name: "Cox's Bazar Express",
		numbers: ['813', '814'],
		origin: 'dhaka',
		destination: 'coxs-bazar',
		layoutId: 'train-night',
		departTimes: ['22:30'],
		returnTimes: ['12:30'],
		offDay: 1,
		rating: 46,
		ratingCount: 13820,
		fareIndex: 1.25
	},
	{
		id: 'parjatak-express',
		name: 'Parjatak Express',
		numbers: ['815', '816'],
		origin: 'dhaka',
		destination: 'coxs-bazar',
		layoutId: 'train-intercity',
		departTimes: ['06:15'],
		returnTimes: ['20:00'],
		offDay: 3,
		rating: 44,
		ratingCount: 9640,
		fareIndex: 1.2
	},

	{
		id: 'paharika-express',
		name: 'Paharika Express',
		numbers: ['719', '720'],
		origin: 'chattogram',
		destination: 'sylhet',
		layoutId: 'train-intercity',
		departTimes: ['08:15'],
		returnTimes: ['10:15'],
		offDay: 1,
		rating: 40,
		ratingCount: 5210,
		fareIndex: 0.98
	},
	{
		id: 'udayan-express',
		name: 'Udayan Express',
		numbers: ['723', '724'],
		origin: 'chattogram',
		destination: 'sylhet',
		layoutId: 'train-night',
		departTimes: ['21:45'],
		returnTimes: ['20:30'],
		offDay: 0,
		rating: 41,
		ratingCount: 4870,
		fareIndex: 1.02
	},
	{
		id: 'meghna-express',
		name: 'Meghna Express',
		numbers: ['729', '730'],
		origin: 'chattogram',
		destination: 'chandpur',
		layoutId: 'train-intercity',
		departTimes: ['17:15'],
		returnTimes: ['05:00'],
		rating: 36,
		ratingCount: 3140,
		fareIndex: 0.82
	},
	{
		id: 'upakul-express',
		name: 'Upakul Express',
		numbers: ['711', '712'],
		origin: 'dhaka',
		destination: 'noakhali',
		layoutId: 'train-intercity',
		departTimes: ['15:20'],
		returnTimes: ['06:00'],
		offDay: 3,
		rating: 37,
		ratingCount: 3960,
		fareIndex: 0.88
	},

	{
		id: 'kapotaksha-express',
		name: 'Kapotaksha Express',
		numbers: ['715', '716'],
		origin: 'khulna',
		destination: 'rajshahi',
		layoutId: 'train-intercity',
		departTimes: ['06:45'],
		returnTimes: ['14:20'],
		offDay: 6,
		rating: 38,
		ratingCount: 3420,
		fareIndex: 0.9
	},
	{
		id: 'sagardari-express',
		name: 'Sagardari Express',
		numbers: ['761', '762'],
		origin: 'khulna',
		destination: 'rajshahi',
		layoutId: 'train-intercity',
		departTimes: ['16:00'],
		returnTimes: ['06:40'],
		offDay: 1,
		rating: 39,
		ratingCount: 2980,
		fareIndex: 0.92
	},
	{
		id: 'rupsha-express',
		name: 'Rupsha Express',
		numbers: ['727', '728'],
		origin: 'khulna',
		destination: 'dinajpur',
		layoutId: 'train-intercity',
		departTimes: ['07:15'],
		returnTimes: ['08:30'],
		offDay: 4,
		rating: 38,
		ratingCount: 3260,
		fareIndex: 0.95
	},
	{
		id: 'simanta-express',
		name: 'Simanta Express',
		numbers: ['747', '748'],
		origin: 'khulna',
		destination: 'nilphamari',
		layoutId: 'train-night',
		departTimes: ['21:15'],
		returnTimes: ['18:45'],
		rating: 39,
		ratingCount: 2740,
		fareIndex: 0.98
	},
	{
		id: 'barendra-express',
		name: 'Barendra Express',
		numbers: ['731', '732'],
		origin: 'rajshahi',
		destination: 'nilphamari',
		layoutId: 'train-intercity',
		departTimes: ['15:00'],
		returnTimes: ['06:20'],
		offDay: 0,
		rating: 37,
		ratingCount: 2410,
		fareIndex: 0.88
	},
	{
		id: 'titumir-express',
		name: 'Titumir Express',
		numbers: ['733', '734'],
		origin: 'rajshahi',
		destination: 'panchagarh',
		layoutId: 'train-intercity',
		departTimes: ['06:20'],
		returnTimes: ['13:00'],
		offDay: 3,
		rating: 38,
		ratingCount: 2180,
		fareIndex: 0.9
	}
];
